### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by l50** [Sandarmann/dr_robot#19]
Seeing things like this:
https://i
http://i
https://q
http://q
https://r
http://r
https://s
http://s

Ran this command: 
```
drrobot gather -turbo -hack -dump -amass <target site>
```

**Comment by CrimsonK1ng** [comment]
I believe this is an issue with the regex group(1) for hostnames. Currently testing to see if removing the group(1) fixes this

**Comment by CrimsonK1ng** [comment]
Fixed in refactor
