### ISSUE TITLE
Error running recon-ng

### ISSUE THREAD

**Issue by l50** [Sandarmann/dr_robot#20]
It's pointing to the wrong repository. It should point to https://github.com/lanmaster53/recon-ng and not https://LaNMaSteR53@bitbucket.org/LaNMaSteR53/recon-ng.git

**Comment by l50** [comment]
A component of the fix in the `config.json` file:
```
"src": "https://github.com/lanmaster53/recon-ng",
```

**Comment by CrimsonK1ng** [comment]
Fixed in upcoming refactor
